import 'package:flutter/material.dart';

import '../dominio/modelos/provincia.dart';
import '../dominio/modelos/destino_destacado.dart';
import '../dominio/modelos/ranking_destino.dart';

/// Fuente de datos local con la información de las 13 provincias de Cusco
/// y sus destinos turísticos principales.
///
/// Esta clase está preparada para ser reemplazada por una fuente remota
/// (Supabase) cuando se integre el backend.
class ProvinciasDataSourceLocal {
  /// Las 13 provincias de la región Cusco.
  static List<Provincia> obtenerProvincias() {
    return const [
      Provincia(
        id: 'cusco',
        nombre: 'Cusco',
        nombreCorto: 'Cusco',
        rutaSvg: 'assets/mapas/cusco.svg',
        destinoPrincipal: 'Centro Histórico',
        descripcion:
            'Capital del imperio Inca y Patrimonio de la Humanidad. Su centro histórico alberga construcciones coloniales sobre cimientos incas.',
        colorBase: Color(0xFFC9A84C),
        posicionCentro: Offset(0.56, 0.55),
        capital: 'Cusco',
        altitudMedia: 3400,
      ),
      Provincia(
        id: 'urubamba',
        nombre: 'Urubamba',
        nombreCorto: 'Urubamba',
        rutaSvg: 'assets/mapas/urubamba.svg',
        destinoPrincipal: 'Machu Picchu',
        descripcion:
            'Corazón del Valle Sagrado. Aquí se encuentra la ciudadela de Machu Picchu, una de las siete maravillas del mundo moderno.',
        colorBase: Color(0xFF2D6A4F),
        posicionCentro: Offset(0.48, 0.49),
        capital: 'Urubamba',
        altitudMedia: 2871,
      ),
      Provincia(
        id: 'la_convencion',
        nombre: 'La Convención',
        nombreCorto: 'La Conv.',
        rutaSvg: 'assets/mapas/la_convencion.svg',
        destinoPrincipal: 'Quillabamba',
        descripcion:
            'La provincia más grande de Cusco. Zona de selva y ceja de selva con cafetales, ríos caudalosos y biodiversidad única.',
        colorBase: Color(0xFF1B4332),
        posicionCentro: Offset(0.31, 0.27),
        capital: 'Quillabamba',
        altitudMedia: 1050,
      ),
      Provincia(
        id: 'calca',
        nombre: 'Calca',
        nombreCorto: 'Calca',
        rutaSvg: 'assets/mapas/calca.svg',
        destinoPrincipal: 'Huchuy Qosqo',
        descripcion:
            'Valle interandino con lagunas glaciares, sitios arqueológicos y pueblos tradicionales a lo largo del río Vilcanota.',
        colorBase: Color(0xFF40916C),
        posicionCentro: Offset(0.54, 0.43),
        capital: 'Calca',
        altitudMedia: 2926,
      ),
      Provincia(
        id: 'paucartambo',
        nombre: 'Paucartambo',
        nombreCorto: 'Paucart.',
        rutaSvg: 'assets/mapas/paucartambo.svg',
        destinoPrincipal: 'Tres Cruces',
        descripcion:
            'Puerta de entrada a la selva cusqueña. Famosa por su fiesta de la Virgen del Carmen y el mirador de Tres Cruces de Oro.',
        colorBase: Color(0xFFB07D62),
        posicionCentro: Offset(0.68, 0.47),
        capital: 'Paucartambo',
        altitudMedia: 2906,
      ),
      Provincia(
        id: 'anta',
        nombre: 'Anta',
        nombreCorto: 'Anta',
        rutaSvg: 'assets/mapas/anta.svg',
        destinoPrincipal: 'Pampa de Anta',
        descripcion:
            'Llanura fértil al oeste de Cusco. Zona agrícola con lagunas, humedales y la ruta hacia Abancay.',
        colorBase: Color(0xFF556B2F),
        posicionCentro: Offset(0.46, 0.54),
        capital: 'Anta',
        altitudMedia: 3337,
      ),
      Provincia(
        id: 'quispicanchi',
        nombre: 'Quispicanchi',
        nombreCorto: 'Quispic.',
        rutaSvg: 'assets/mapas/quispicanchi.svg',
        destinoPrincipal: 'Tipón',
        descripcion:
            'Parque arqueológico de Tipón con sus fuentes de agua ceremoniales. Ruta hacia Ocongate y el nevado Ausangate.',
        colorBase: Color(0xFFCC8B65),
        posicionCentro: Offset(0.79, 0.55),
        capital: 'Urcos',
        altitudMedia: 3150,
      ),
      Provincia(
        id: 'paruro',
        nombre: 'Paruro',
        nombreCorto: 'Paruro',
        rutaSvg: 'assets/mapas/paruro.svg',
        destinoPrincipal: 'Maukallaqta',
        descripcion:
            'Provincia de valles profundos y pueblos quechuas. Destaca el sitio arqueológico de Maukallaqta y sus puentes coloniales.',
        colorBase: Color(0xFFB87333),
        posicionCentro: Offset(0.57, 0.63),
        capital: 'Paruro',
        altitudMedia: 3051,
      ),
      Provincia(
        id: 'acomayo',
        nombre: 'Acomayo',
        nombreCorto: 'Acomayo',
        rutaSvg: 'assets/mapas/acomayo.svg',
        destinoPrincipal: 'Puente Colgante de Queswachaka',
        descripcion:
            'Hogar del último puente colgante inca, renovado cada año. Territorio de lagunas alto andinas y tradiciones vivas.',
        colorBase: Color(0xFF6B8E23),
        posicionCentro: Offset(0.67, 0.67),
        capital: 'Acomayo',
        altitudMedia: 3207,
      ),
      Provincia(
        id: 'canchis',
        nombre: 'Canchis',
        nombreCorto: 'Canchis',
        rutaSvg: 'assets/mapas/canchis.svg',
        destinoPrincipal: 'Raqchi',
        descripcion:
            'Templo de Wiracocha en Raqchi, uno de los más grandes del Tahuantinsuyo. Centro de comercio y artesanía textil.',
        colorBase: Color(0xFFA0522D),
        posicionCentro: Offset(0.75, 0.72),
        capital: 'Sicuani',
        altitudMedia: 3548,
      ),
      Provincia(
        id: 'canas',
        nombre: 'Canas',
        nombreCorto: 'Canas',
        rutaSvg: 'assets/mapas/canas.svg',
        destinoPrincipal: 'Laguna de Langui-Layo',
        descripcion:
            'Tierra de Túpac Amaru II. Extensas pampas alto andinas con lagunas glaciares y una fuerte identidad cultural quechua.',
        colorBase: Color(0xFFD4A574),
        posicionCentro: Offset(0.73, 0.74),
        capital: 'Yanaoca',
        altitudMedia: 3910,
      ),
      Provincia(
        id: 'espinar',
        nombre: 'Espinar',
        nombreCorto: 'Espinar',
        rutaSvg: 'assets/mapas/espinar.svg',
        destinoPrincipal: 'Cañón del Apurímac',
        descripcion:
            'Provincia ganadera con extensas punas. Destaca el Cañón del Apurímac, uno de los más profundos del mundo.',
        colorBase: Color(0xFF8B8C89),
        posicionCentro: Offset(0.71, 0.82),
        capital: 'Yauri',
        altitudMedia: 3915,
      ),
      Provincia(
        id: 'chumbivilcas',
        nombre: 'Chumbivilcas',
        nombreCorto: 'Chumbiv.',
        rutaSvg: 'assets/mapas/chumbivilcas.svg',
        destinoPrincipal: 'Danza de los Cóndores',
        descripcion:
            'Tierra de jinetes y el Takanakuy. Famosa por sus tradiciones ecuestres, corridas de toros andinos y fiestas costumbristas.',
        colorBase: Color(0xFF8B6914),
        posicionCentro: Offset(0.64, 0.73),
        capital: 'Santo Tomás',
        altitudMedia: 3660,
      ),
    ];
  }

  /// Destinos destacados de ejemplo para cada provincia.
  /// Preparado para ser reemplazado por datos de Supabase.
  static Map<String, List<DestinoDestacado>> obtenerDestinosPorProvincia() {
    return {
      'urubamba': const [
        DestinoDestacado(
          id: 'machu_picchu',
          nombre: 'Machu Picchu',
          provinciaId: 'urubamba',
          descripcion: 'Ciudadela inca, maravilla del mundo moderno',
          visitas: 4520,
          favoritos: 3890,
          crecimientoMensual: 12.5,
          posicion: 1,
        ),
        DestinoDestacado(
          id: 'ollantaytambo',
          nombre: 'Ollantaytambo',
          provinciaId: 'urubamba',
          descripcion: 'Fortaleza inca y pueblo vivo del Valle Sagrado',
          visitas: 2870,
          favoritos: 2100,
          crecimientoMensual: 8.3,
          posicion: 2,
        ),
        DestinoDestacado(
          id: 'maras',
          nombre: 'Salineras de Maras',
          provinciaId: 'urubamba',
          descripcion: 'Miles de pozas de sal sobre la ladera andina',
          visitas: 2340,
          favoritos: 1980,
          crecimientoMensual: 15.2,
          posicion: 3,
        ),
      ],
      'cusco': const [
        DestinoDestacado(
          id: 'centro_historico',
          nombre: 'Centro Histórico',
          provinciaId: 'cusco',
          descripcion: 'Patrimonio de la Humanidad con arquitectura inca y colonial',
          visitas: 5200,
          favoritos: 4100,
          crecimientoMensual: 5.1,
          posicion: 1,
        ),
        DestinoDestacado(
          id: 'sacsayhuaman',
          nombre: 'Sacsayhuamán',
          provinciaId: 'cusco',
          descripcion: 'Fortaleza ceremonial con muros megalíticos',
          visitas: 3800,
          favoritos: 3200,
          crecimientoMensual: 3.7,
          posicion: 2,
        ),
        DestinoDestacado(
          id: 'qenqo',
          nombre: 'Q\'enqo',
          provinciaId: 'cusco',
          descripcion: 'Anfiteatro de roca y santuario subterráneo',
          visitas: 2100,
          favoritos: 1650,
          crecimientoMensual: 6.2,
          posicion: 3,
        ),
      ],
      'calca': const [
        DestinoDestacado(
          id: 'huchuy_qosqo',
          nombre: 'Huchuy Qosqo',
          provinciaId: 'calca',
          descripcion: 'Sitio arqueológico con vista al Valle Sagrado',
          visitas: 890,
          favoritos: 720,
          crecimientoMensual: 22.1,
          posicion: 1,
        ),
        DestinoDestacado(
          id: 'lares',
          nombre: 'Termas de Lares',
          provinciaId: 'calca',
          descripcion: 'Aguas termales en medio de montañas nevadas',
          visitas: 670,
          favoritos: 540,
          crecimientoMensual: 18.4,
          posicion: 2,
        ),
        DestinoDestacado(
          id: 'pisac',
          nombre: 'Pisac',
          provinciaId: 'calca',
          descripcion: 'Mercado artesanal y parque arqueológico',
          visitas: 1450,
          favoritos: 1100,
          crecimientoMensual: 7.8,
          posicion: 3,
        ),
      ],
      'la_convencion': const [
        DestinoDestacado(
          id: 'quillabamba',
          nombre: 'Quillabamba',
          provinciaId: 'la_convencion',
          descripcion: 'Ciudad de la eterna primavera, capital del café',
          visitas: 780,
          favoritos: 560,
          crecimientoMensual: 9.3,
          posicion: 1,
        ),
        DestinoDestacado(
          id: 'choquequirao',
          nombre: 'Choquequirao',
          provinciaId: 'la_convencion',
          descripcion: 'Hermana de Machu Picchu, aún sin turismo masivo',
          visitas: 320,
          favoritos: 290,
          crecimientoMensual: 35.0,
          posicion: 2,
        ),
        DestinoDestacado(
          id: 'echarate',
          nombre: 'Echarate',
          provinciaId: 'la_convencion',
          descripcion: 'Selva alta con cascadas y biodiversidad única',
          visitas: 210,
          favoritos: 180,
          crecimientoMensual: 12.0,
          posicion: 3,
        ),
      ],
      'paucartambo': const [
        DestinoDestacado(
          id: 'tres_cruces',
          nombre: 'Tres Cruces de Oro',
          provinciaId: 'paucartambo',
          descripcion: 'Amanecer más espectacular del mundo',
          visitas: 540,
          favoritos: 480,
          crecimientoMensual: 28.6,
          posicion: 1,
        ),
        DestinoDestacado(
          id: 'virgen_carmen',
          nombre: 'Fiesta Virgen del Carmen',
          provinciaId: 'paucartambo',
          descripcion: 'Patrimonio Cultural de la Nación, danzas tradicionales',
          visitas: 890,
          favoritos: 760,
          crecimientoMensual: 4.2,
          posicion: 2,
        ),
        DestinoDestacado(
          id: 'puente_carlos_iii',
          nombre: 'Puente Carlos III',
          provinciaId: 'paucartambo',
          descripcion: 'Puente colonial sobre el río Mapacho',
          visitas: 320,
          favoritos: 210,
          crecimientoMensual: 6.5,
          posicion: 3,
        ),
      ],
      'quispicanchi': const [
        DestinoDestacado(
          id: 'tipon',
          nombre: 'Tipón',
          provinciaId: 'quispicanchi',
          descripcion: 'Fuentes ceremoniales y terrazas de cultivo',
          visitas: 1200,
          favoritos: 950,
          crecimientoMensual: 11.3,
          posicion: 1,
        ),
        DestinoDestacado(
          id: 'ausangate',
          nombre: 'Nevado Ausangate',
          provinciaId: 'quispicanchi',
          descripcion: 'Trekking de alta montaña y Montaña de Colores',
          visitas: 2100,
          favoritos: 1800,
          crecimientoMensual: 25.0,
          posicion: 2,
        ),
        DestinoDestacado(
          id: 'andahuaylillas',
          nombre: 'Andahuaylillas',
          provinciaId: 'quispicanchi',
          descripcion: 'Capilla Sixtina de América con arte barroco',
          visitas: 780,
          favoritos: 620,
          crecimientoMensual: 8.1,
          posicion: 3,
        ),
      ],
      'anta': const [
        DestinoDestacado(
          id: 'pampa_anta',
          nombre: 'Pampa de Anta',
          provinciaId: 'anta',
          descripcion: 'Llanura fértil con lagunas y humedales',
          visitas: 340,
          favoritos: 220,
          crecimientoMensual: 5.0,
          posicion: 1,
        ),
        DestinoDestacado(
          id: 'zurite',
          nombre: 'Zurite',
          provinciaId: 'anta',
          descripcion: 'Terrazas incas circulares y vistas panorámicas',
          visitas: 280,
          favoritos: 190,
          crecimientoMensual: 14.0,
          posicion: 2,
        ),
        DestinoDestacado(
          id: 'laguna_huaypo',
          nombre: 'Laguna Huaypo',
          provinciaId: 'anta',
          descripcion: 'Laguna alto andina para pesca y kayak',
          visitas: 190,
          favoritos: 130,
          crecimientoMensual: 20.0,
          posicion: 3,
        ),
      ],
      'paruro': const [
        DestinoDestacado(
          id: 'maukallaqta',
          nombre: 'Maukallaqta',
          provinciaId: 'paruro',
          descripcion: 'Sitio arqueológico preinca en las alturas',
          visitas: 180,
          favoritos: 130,
          crecimientoMensual: 32.0,
          posicion: 1,
        ),
        DestinoDestacado(
          id: 'puente_colonial_paruro',
          nombre: 'Puente Colonial',
          provinciaId: 'paruro',
          descripcion: 'Arquitectura colonial sobre el río Apurímac',
          visitas: 120,
          favoritos: 80,
          crecimientoMensual: 10.0,
          posicion: 2,
        ),
        DestinoDestacado(
          id: 'aguas_termales_paruro',
          nombre: 'Aguas Termales',
          provinciaId: 'paruro',
          descripcion: 'Fuentes termales naturales en los Andes',
          visitas: 90,
          favoritos: 60,
          crecimientoMensual: 15.0,
          posicion: 3,
        ),
      ],
      'acomayo': const [
        DestinoDestacado(
          id: 'queswachaka',
          nombre: 'Puente Q\'eswachaka',
          provinciaId: 'acomayo',
          descripcion: 'Último puente colgante inca, renovado cada junio',
          visitas: 650,
          favoritos: 580,
          crecimientoMensual: 19.5,
          posicion: 1,
        ),
        DestinoDestacado(
          id: 'laguna_pomacanchi',
          nombre: 'Laguna Pomacanchi',
          provinciaId: 'acomayo',
          descripcion: 'Laguna alto andina con aves migratorias',
          visitas: 230,
          favoritos: 170,
          crecimientoMensual: 8.0,
          posicion: 2,
        ),
        DestinoDestacado(
          id: 'sangarara',
          nombre: 'Sangarará',
          provinciaId: 'acomayo',
          descripcion: 'Iglesia colonial y batalla histórica',
          visitas: 110,
          favoritos: 80,
          crecimientoMensual: 5.0,
          posicion: 3,
        ),
      ],
      'canchis': const [
        DestinoDestacado(
          id: 'raqchi',
          nombre: 'Templo de Raqchi',
          provinciaId: 'canchis',
          descripcion: 'Templo de Wiracocha, el más grande del Tahuantinsuyo',
          visitas: 920,
          favoritos: 780,
          crecimientoMensual: 7.3,
          posicion: 1,
        ),
        DestinoDestacado(
          id: 'sicuani',
          nombre: 'Sicuani',
          provinciaId: 'canchis',
          descripcion: 'Capital ganadera con ferias de textiles andinos',
          visitas: 560,
          favoritos: 340,
          crecimientoMensual: 3.0,
          posicion: 2,
        ),
        DestinoDestacado(
          id: 'la_raya',
          nombre: 'Abra La Raya',
          provinciaId: 'canchis',
          descripcion: 'Paso a 4335 msnm, frontera natural con Puno',
          visitas: 430,
          favoritos: 310,
          crecimientoMensual: 6.0,
          posicion: 3,
        ),
      ],
      'canas': const [
        DestinoDestacado(
          id: 'langui_layo',
          nombre: 'Laguna Langui-Layo',
          provinciaId: 'canas',
          descripcion: 'Laguna glaciar de aguas turquesas a 3950 msnm',
          visitas: 280,
          favoritos: 210,
          crecimientoMensual: 25.0,
          posicion: 1,
        ),
        DestinoDestacado(
          id: 'yanaoca',
          nombre: 'Yanaoca',
          provinciaId: 'canas',
          descripcion: 'Capital de Canas, tierra de Túpac Amaru II',
          visitas: 180,
          favoritos: 120,
          crecimientoMensual: 10.0,
          posicion: 2,
        ),
        DestinoDestacado(
          id: 'pampamarca_canas',
          nombre: 'Pampamarca',
          provinciaId: 'canas',
          descripcion: 'Pueblo colonial con plaza histórica',
          visitas: 90,
          favoritos: 60,
          crecimientoMensual: 8.0,
          posicion: 3,
        ),
      ],
      'espinar': const [
        DestinoDestacado(
          id: 'canon_apurimac',
          nombre: 'Cañón del Apurímac',
          provinciaId: 'espinar',
          descripcion: 'Uno de los cañones más profundos del mundo',
          visitas: 320,
          favoritos: 280,
          crecimientoMensual: 18.0,
          posicion: 1,
        ),
        DestinoDestacado(
          id: 'yauri',
          nombre: 'Yauri',
          provinciaId: 'espinar',
          descripcion: 'Capital ganadera con fiestas patronales vibrantes',
          visitas: 190,
          favoritos: 120,
          crecimientoMensual: 4.0,
          posicion: 2,
        ),
        DestinoDestacado(
          id: 'tres_cañones',
          nombre: 'Tres Cañones',
          provinciaId: 'espinar',
          descripcion: 'Formaciones rocosas erosionadas por millones de años',
          visitas: 150,
          favoritos: 130,
          crecimientoMensual: 30.0,
          posicion: 3,
        ),
      ],
      'chumbivilcas': const [
        DestinoDestacado(
          id: 'danza_condores',
          nombre: 'Danza de los Cóndores',
          provinciaId: 'chumbivilcas',
          descripcion: 'Ritual ancestral con cóndores y jinetes',
          visitas: 410,
          favoritos: 380,
          crecimientoMensual: 14.0,
          posicion: 1,
        ),
        DestinoDestacado(
          id: 'takanakuy',
          nombre: 'Festival Takanakuy',
          provinciaId: 'chumbivilcas',
          descripcion: 'Combate ritual cada 25 de diciembre',
          visitas: 560,
          favoritos: 490,
          crecimientoMensual: 22.0,
          posicion: 2,
        ),
        DestinoDestacado(
          id: 'santo_tomas',
          nombre: 'Santo Tomás',
          provinciaId: 'chumbivilcas',
          descripcion: 'Capital de los jinetes andinos',
          visitas: 210,
          favoritos: 150,
          crecimientoMensual: 6.0,
          posicion: 3,
        ),
      ],
    };
  }

  /// Ranking mensual global (Top 3 de toda la región).
  static RankingDestino obtenerRankingMensual() {
    return const RankingDestino(
      mes: 8,
      anio: 2026,
      destinos: [
        DestinoDestacado(
          id: 'machu_picchu',
          nombre: 'Machu Picchu',
          provinciaId: 'urubamba',
          descripcion: 'Ciudadela inca, maravilla del mundo moderno',
          visitas: 4520,
          favoritos: 3890,
          crecimientoMensual: 12.5,
          posicion: 1,
        ),
        DestinoDestacado(
          id: 'centro_historico',
          nombre: 'Centro Histórico de Cusco',
          provinciaId: 'cusco',
          descripcion: 'Patrimonio de la Humanidad con arquitectura inca y colonial',
          visitas: 5200,
          favoritos: 4100,
          crecimientoMensual: 5.1,
          posicion: 2,
        ),
        DestinoDestacado(
          id: 'ausangate',
          nombre: 'Montaña de Colores',
          provinciaId: 'quispicanchi',
          descripcion: 'Trekking de alta montaña y paisajes multicolores',
          visitas: 2100,
          favoritos: 1800,
          crecimientoMensual: 25.0,
          posicion: 3,
        ),
      ],
    );
  }
}
