import '../../../nucleo/recursos/catalogo_imagenes_haku.dart';

import '../dominio/modelos/modelo_ruta.dart';

/// Fuente local de rutas (preparada para reemplazo por backend).
class RutasDataSourceLocal {
  static const List<ModeloRuta> _rutas = [
    ModeloRuta(
      id: 'ruta_inca_clasica',
      titulo: 'Ruta Inca Clásica',
      subtitulo: 'Camino ancestral al santuario',
      descripcion:
          'El legendario Camino Inca hasta Machu Picchu. Cuatro días de trekking entre bosques de nubes, ruinas y vistas inolvidables del Valle Sagrado.',
      imagenUrl: CatalogoImagenesHaku.machuPicchu,
      categoria: CategoriaRuta.recomendadas,
      cantidadLugares: 5,
      dias: 4,
      distancia: '42 km',
      nivelDificultad: 4,
      dificultadTexto: 'Alta',
      altitud: '4,200 m.s.n.m.',
      tiempoCaminata: '4 días',
      mejorEpoca: 'Mayo - Septiembre',
      etiquetas: ['Aventura', 'Historia', 'Trekking'],
      calificacion: 4.9,
      cantidadResenas: 3120,
      textoBoton: 'Cómo llegar',
      tipoSitio: 'Trekking',
      puntoPartida: 'Km 82 — Piscacucho',
      transporte: 'Tren + bus / colectivo desde Cusco',
      comoLlegar:
          'Desde Cusco toma tren o colectivo a Ollantaytambo y continúa hasta el Km 82 (Piscacucho), punto de control donde inicia el Camino Inca. Reserva anticipada obligatoria.',
      tips: [
        'Permiso del Camino Inca con 3–6 meses de anticipación',
        'Aclimatación mínima 2 días en Cusco',
        'Llevar bastones y capas para lluvia',
      ],
      puntos: [
        PuntoRuta(
          id: 'ri1',
          nombre: 'Piscacucho (Km 82)',
          tipo: 'inicio',
          lat: -13.2245,
          lng: -72.4340,
          nota: 'Control de ingreso',
        ),
        PuntoRuta(
          id: 'ri2',
          nombre: 'Wayllabamba',
          tipo: 'parada',
          lat: -13.2360,
          lng: -72.4680,
          nota: 'Campamento día 1',
        ),
        PuntoRuta(
          id: 'ri3',
          nombre: 'Warmiwañusca',
          tipo: 'parada',
          lat: -13.2520,
          lng: -72.5100,
          nota: 'Paso más alto ~4,200 m',
        ),
        PuntoRuta(
          id: 'ri4',
          nombre: 'Wiñay Wayna',
          tipo: 'parada',
          lat: -13.1720,
          lng: -72.5360,
          nota: 'Ruinas y campamento',
        ),
        PuntoRuta(
          id: 'ri5',
          nombre: 'Machu Picchu',
          tipo: 'destino',
          lat: -13.1631,
          lng: -72.5450,
          nota: 'Ciudadela',
        ),
      ],
    ),
    ModeloRuta(
      id: 'valle_sagrado',
      titulo: 'Valle Sagrado',
      subtitulo: 'Pisac, Ollantaytambo y más',
      descripcion:
          'Recorre los pueblos vivos del Valle Sagrado: mercados, terrazas agrícolas y fortalezas incas en un circuito de dos días.',
      imagenUrl: CatalogoImagenesHaku.moray,
      categoria: CategoriaRuta.recomendadas,
      cantidadLugares: 6,
      dias: 2,
      distancia: '85 km',
      nivelDificultad: 2,
      dificultadTexto: 'Moderada',
      altitud: '2,800 m.s.n.m.',
      tiempoCaminata: '2 días',
      mejorEpoca: 'Abril - Octubre',
      etiquetas: ['Cultura', 'Pueblos', 'Miradores'],
      calificacion: 4.7,
      cantidadResenas: 2180,
      textoBoton: 'Mapa',
      tipoSitio: 'Circuito',
      puntoPartida: 'Plaza de Armas, Cusco',
      transporte: 'Colectivo / taxi / tour privado',
      comoLlegar:
          'Sale desde Cusco por la carretera hacia Pisac (≈45 min). Continúa a Urubamba y Ollantaytambo. Puedes hacerlo en un día largo o dormir en el valle.',
      tips: const [
        'Mercado de Pisac abre fuerte los martes/jueves/domingo',
        'Llevar efectivo en soles para artesanos',
      ],
      puntos: [
        PuntoRuta(
          id: 'vs0',
          nombre: 'Cusco',
          tipo: 'inicio',
          lat: -13.5167,
          lng: -71.9788,
        ),
        PuntoRuta(
          id: 'vs1',
          nombre: 'Pisac',
          tipo: 'parada',
          lat: -13.4225,
          lng: -71.8467,
          nota: 'Mercado y ruinas',
        ),
        PuntoRuta(
          id: 'vs2',
          nombre: 'Urubamba',
          tipo: 'parada',
          lat: -13.3067,
          lng: -72.1161,
        ),
        PuntoRuta(
          id: 'vs3',
          nombre: 'Ollantaytambo',
          tipo: 'destino',
          lat: -13.2581,
          lng: -72.2636,
          nota: 'Fortaleza viva',
        ),
      ],
    ),
    ModeloRuta(
      id: 'cusco_historico',
      titulo: 'Cusco Histórico',
      subtitulo: 'Centro y Sacsayhuamán',
      descripcion:
          'Camina el casco histórico cusqueño: Plaza de Armas, Qorikancha y la fortaleza de Sacsayhuamán en una jornada cultural intensa.',
      imagenUrl: CatalogoImagenesHaku.ausangate,
      categoria: CategoriaRuta.recomendadas,
      cantidadLugares: 4,
      dias: 1,
      distancia: '8 km',
      nivelDificultad: 1,
      dificultadTexto: 'Baja',
      altitud: '3,399 m.s.n.m.',
      tiempoCaminata: '5 - 6 horas',
      mejorEpoca: 'Todo el año',
      etiquetas: ['Historia', 'Ciudad', 'Arquitectura'],
      calificacion: 4.8,
      cantidadResenas: 4560,
      textoBoton: 'Empezar',
      tipoSitio: 'Urbana',
      puntoPartida: 'Plaza de Armas',
      transporte: 'A pie (todo el circuito)',
      comoLlegar:
          'Comienza en la Plaza de Armas. Baja a Qorikancha, sube por San Blas y continúa hasta Sacsayhuamán (taxi opcional en el tramo final).',
      tips: const [
        'Boleto turístico parcial cubre Sacsayhuamán',
        'Hidrátate: la altura se siente al subir',
      ],
      puntos: [
        PuntoRuta(
          id: 'ch1',
          nombre: 'Plaza de Armas',
          tipo: 'inicio',
          lat: -13.5167,
          lng: -71.9788,
        ),
        PuntoRuta(
          id: 'ch2',
          nombre: 'Qorikancha',
          tipo: 'parada',
          lat: -13.5205,
          lng: -71.9753,
        ),
        PuntoRuta(
          id: 'ch3',
          nombre: 'San Blas',
          tipo: 'parada',
          lat: -13.5140,
          lng: -71.9758,
        ),
        PuntoRuta(
          id: 'ch4',
          nombre: 'Sacsayhuamán',
          tipo: 'destino',
          lat: -13.5094,
          lng: -71.9817,
        ),
      ],
    ),
    ModeloRuta(
      id: 'machu_picchu',
      titulo: 'Machu Picchu',
      subtitulo: 'Maravilla del Mundo',
      descripcion:
          'La ciudadela inca más famosa del mundo. Explora templos, plazas y terrazas con vistas al valle del Urubamba.',
      imagenUrl: CatalogoImagenesHaku.ausangate,
      categoria: CategoriaRuta.populares,
      cantidadLugares: 3,
      dias: 1,
      distancia: '12 km',
      nivelDificultad: 2,
      dificultadTexto: 'Moderada',
      altitud: '2,430 m.s.n.m.',
      tiempoCaminata: '3 - 4 horas',
      mejorEpoca: 'Mayo - Septiembre',
      etiquetas: ['Sitio Arqueológico', 'Patrimonio', 'Mirador'],
      calificacion: 4.8,
      cantidadResenas: 2345,
      textoBoton: 'Mapa',
      tipoSitio: 'Sitio Arqueológico',
      puntoPartida: 'Estación Poroy / Ollantaytambo',
      transporte: 'Tren a Aguas Calientes + bus CONSETUR',
      comoLlegar:
          'Tren desde Poroy u Ollantaytambo hasta Aguas Calientes. De ahí, bus a la ciudadela o caminata empinada (≈1.5 h). Entrada con horario.',
      tips: const [
        'Compra tickets con fecha y circuito',
        'Llega al primer bus si quieres menos gente',
      ],
      puntos: [
        PuntoRuta(
          id: 'mp1',
          nombre: 'Ollantaytambo',
          tipo: 'inicio',
          lat: -13.2581,
          lng: -72.2636,
        ),
        PuntoRuta(
          id: 'mp2',
          nombre: 'Aguas Calientes',
          tipo: 'parada',
          lat: -13.1547,
          lng: -72.5255,
        ),
        PuntoRuta(
          id: 'mp3',
          nombre: 'Machu Picchu',
          tipo: 'destino',
          lat: -13.1631,
          lng: -72.5450,
        ),
      ],
    ),
    ModeloRuta(
      id: 'laguna_humantay',
      titulo: 'Laguna Humantay',
      subtitulo: 'Turquesa bajo el Apu',
      descripcion:
          'Ascenso hacia una laguna glaciar de aguas turquesas al pie del nevado Humantay. Una de las caminatas más fotogénicas de Cusco.',
      imagenUrl: CatalogoImagenesHaku.llamaMachu,
      categoria: CategoriaRuta.naturaleza,
      cantidadLugares: 2,
      dias: 1,
      distancia: '6 km',
      nivelDificultad: 3,
      dificultadTexto: 'Moderada',
      altitud: '4,200 m.s.n.m.',
      tiempoCaminata: '1.5 - 2 horas',
      mejorEpoca: 'Abril - Octubre',
      etiquetas: ['Naturaleza', 'Aventura', 'Fotografía'],
      calificacion: 4.9,
      cantidadResenas: 1890,
      textoBoton: 'Cómo llegar',
      tipoSitio: 'Naturaleza',
      puntoPartida: 'Soraypampa',
      transporte: 'Van desde Cusco (salida ~4–5 am)',
      comoLlegar:
          'Van o tour desde Cusco hasta Mollepata y luego Soraypampa. Desde allí, caminata de ~1.5–2 h hasta la laguna. Caballos opcionales en tramos.',
      tips: const [
        'Salida muy temprano para evitar nubes',
        'Bastones ayudan en el último tramo',
      ],
      puntos: [
        PuntoRuta(
          id: 'lh1',
          nombre: 'Cusco',
          tipo: 'inicio',
          lat: -13.5167,
          lng: -71.9788,
        ),
        PuntoRuta(
          id: 'lh2',
          nombre: 'Soraypampa',
          tipo: 'parada',
          lat: -13.3960,
          lng: -72.5750,
          nota: 'Inicio de caminata',
        ),
        PuntoRuta(
          id: 'lh3',
          nombre: 'Laguna Humantay',
          tipo: 'destino',
          lat: -13.3820,
          lng: -72.5880,
        ),
      ],
    ),
    ModeloRuta(
      id: 'vinicunca',
      titulo: 'Montaña de 7 Colores',
      subtitulo: 'Vinicunca y Ausangate',
      descripcion:
          'Trekking de alta montaña hacia Vinicunca, la montaña arcoíris. Paisajes extremos, minerales y el imponente Ausangate.',
      imagenUrl: CatalogoImagenesHaku.moray,
      categoria: CategoriaRuta.naturaleza,
      cantidadLugares: 3,
      dias: 1,
      distancia: '10 km',
      nivelDificultad: 4,
      dificultadTexto: 'Alta',
      altitud: '5,200 m.s.n.m.',
      tiempoCaminata: '5 - 6 horas',
      mejorEpoca: 'Abril - Octubre',
      etiquetas: ['Naturaleza', 'Trekking', 'Alta montaña'],
      calificacion: 4.6,
      cantidadResenas: 2740,
      textoBoton: 'Empezar',
      tipoSitio: 'Trekking',
      puntoPartida: 'Cusipata / Phulawasipata',
      transporte: 'Tour o van privada desde Cusco',
      comoLlegar:
          'Traslado temprano a Cusipata y luego a Phulawasipata. Caminata de altura hasta el mirador. Alternativa: Red Valley.',
      tips: const [
        'Aclimatación obligatoria',
        'Capa térmica + impermeable',
      ],
      puntos: [
        PuntoRuta(
          id: 'vn1',
          nombre: 'Cusco',
          tipo: 'inicio',
          lat: -13.5167,
          lng: -71.9788,
        ),
        PuntoRuta(
          id: 'vn2',
          nombre: 'Phulawasipata',
          tipo: 'parada',
          lat: -13.8700,
          lng: -71.3200,
        ),
        PuntoRuta(
          id: 'vn3',
          nombre: 'Vinicunca',
          tipo: 'destino',
          lat: -13.8697,
          lng: -71.3031,
        ),
      ],
    ),
    ModeloRuta(
      id: 'maras_moray',
      titulo: 'Maras y Moray',
      subtitulo: 'Salineras y laboratorios incas',
      descripcion:
          'Combina las terrazas circulares de Moray con las salineras de Maras en un día de paisaje y cultura andina.',
      imagenUrl: CatalogoImagenesHaku.huacachina,
      categoria: CategoriaRuta.populares,
      cantidadLugares: 2,
      dias: 1,
      distancia: '15 km',
      nivelDificultad: 1,
      dificultadTexto: 'Baja',
      altitud: '3,500 m.s.n.m.',
      tiempoCaminata: '4 - 5 horas',
      mejorEpoca: 'Todo el año',
      etiquetas: ['Cultura', 'Paisaje', 'Fotografía'],
      calificacion: 4.7,
      cantidadResenas: 1650,
      textoBoton: 'Ruta',
      tipoSitio: 'Circuito',
      puntoPartida: 'Urubamba o Cusco',
      transporte: 'Taxi / colectivo / bicicleta',
      comoLlegar:
          'Desde Cusco o Urubamba hacia Maras. Visita Moray primero y luego las salineras. Hay opción en bici desde Urubamba.',
      tips: const [
        'Entrada separada a salineras',
        'Mejor luz al atardecer en Maras',
      ],
      puntos: [
        PuntoRuta(
          id: 'mm1',
          nombre: 'Urubamba',
          tipo: 'inicio',
          lat: -13.3067,
          lng: -72.1161,
        ),
        PuntoRuta(
          id: 'mm2',
          nombre: 'Moray',
          tipo: 'parada',
          lat: -13.3295,
          lng: -72.1956,
        ),
        PuntoRuta(
          id: 'mm3',
          nombre: 'Salineras de Maras',
          tipo: 'destino',
          lat: -13.3000,
          lng: -72.1560,
        ),
      ],
    ),
    ModeloRuta(
      id: 'ceramica_san_blas',
      titulo: 'Moray',
      subtitulo: 'Andenes en círculo',
      descripcion:
          'Laboratorio agrícola inca: terrazas circulares y microclimas que aún se sienten al bajar.',
      imagenUrl: CatalogoImagenesHaku.moray,
      categoria: CategoriaRuta.cultura,
      hilo: HiloCultura.ceramica,
      cantidadLugares: 4,
      dias: 1,
      distancia: '2 km',
      nivelDificultad: 1,
      dificultadTexto: 'Fácil',
      tiempoCaminata: '2 h',
      mejorEpoca: 'Todo el año',
      etiquetas: ['Moray', 'Andenes', 'Valle'],
      calificacion: 4.7,
      cantidadResenas: 520,
      textoBoton: 'Publicar',
      tipoSitio: 'Lugar',
      puntoPartida: 'Maras / Moray',
      transporte: 'Tour o taxi desde Cusco',
      comoLlegar:
          'Desde Cusco hacia Maras–Moray (~1 h). Llega temprano para luz suave en los círculos.',
      tips: const [
        'Bajar al centro: el viento cambia en cada anillo',
      ],
    ),
    ModeloRuta(
      id: 'fogon_san_pedro',
      titulo: 'Ausangate',
      subtitulo: 'El apu de la semana',
      descripcion:
          'Nevado tutelar del sur: lagunas, frío seco y vistas que se abren entre nubes.',
      imagenUrl: CatalogoImagenesHaku.ausangate,
      categoria: CategoriaRuta.cultura,
      hilo: HiloCultura.comida,
      cantidadLugares: 1,
      dias: 1,
      distancia: '1 km',
      nivelDificultad: 1,
      dificultadTexto: 'Fácil',
      tiempoCaminata: '1 h',
      mejorEpoca: 'Todo el año',
      etiquetas: ['Ausangate', 'Nevado', 'Altura'],
      calificacion: 4.9,
      cantidadResenas: 810,
      textoBoton: 'Publicar',
      tipoSitio: 'Nevado',
      puntoPartida: 'Tinki',
      transporte: 'Bus o tour desde Cusco',
      comoLlegar:
          'Salida temprano hacia Tinki / Pacchanta. Lleva abrigo: el apu no perdona.',
      tips: const [
        'Hidratación y ritmo lento desde el primer km',
      ],
    ),
    ModeloRuta(
      id: 'teatro_inti_raymi',
      titulo: 'Machu Picchu',
      subtitulo: 'Vista de la semana',
      descripcion:
          'Ciudadela en la cresta: terrazas, niebla y la primera vez que se ve completa.',
      imagenUrl: CatalogoImagenesHaku.machuPicchu,
      categoria: CategoriaRuta.cultura,
      hilo: HiloCultura.teatro,
      cantidadLugares: 3,
      dias: 1,
      distancia: '5 km',
      nivelDificultad: 2,
      dificultadTexto: 'Moderada',
      tiempoCaminata: '1 día',
      mejorEpoca: '24 de junio',
      etiquetas: ['Machu Picchu', 'Patrimonio'],
      calificacion: 4.9,
      cantidadResenas: 2200,
      textoBoton: 'Publicar',
      tipoSitio: 'Patrimonio',
      puntoPartida: 'Aguas Calientes',
      transporte: 'Tren + bus',
      comoLlegar:
          'Tren a Aguas Calientes y bus a la ciudadela. Reserva entrada con tiempo.',
      tips: const [
        'Llegar al primer bus si quieres menos gente',
      ],
    ),
    ModeloRuta(
      id: 'pintura_san_blas',
      titulo: 'Camino con llamas',
      subtitulo: 'Encuentro en la ruta',
      descripcion:
          'Llamas en el tramo hacia la ciudadela: paciencia, fotos y respeto al pastoreo.',
      imagenUrl: CatalogoImagenesHaku.llamaMachu,
      categoria: CategoriaRuta.cultura,
      hilo: HiloCultura.pintura,
      cantidadLugares: 3,
      dias: 1,
      distancia: '2 km',
      nivelDificultad: 1,
      dificultadTexto: 'Fácil',
      tiempoCaminata: '2 h',
      mejorEpoca: 'Todo el año',
      etiquetas: ['Llamas', 'Camino', 'Foto'],
      calificacion: 4.6,
      cantidadResenas: 340,
      textoBoton: 'Publicar',
      tipoSitio: 'Naturaleza',
      puntoPartida: 'Camino a Machu Picchu',
      transporte: 'A pie',
      comoLlegar:
          'En el trayecto peatonal hacia miradores. No forzar el acercamiento a los animales.',
      tips: const [
        'Foto con zoom; ellas deciden la distancia',
      ],
    ),
  ];

  static List<ModeloRuta> obtenerTodas() => List.unmodifiable(_rutas);

  static List<ModeloRuta> obtenerPorCategoria(CategoriaRuta categoria) {
    return _rutas.where((r) => r.categoria == categoria).toList();
  }

  static List<ModeloRuta> obtenerCultura() =>
      _rutas.where((r) => r.hilo != HiloCultura.camino).toList();

  static ModeloRuta? obtenerPorId(String id) {
    try {
      return _rutas.firstWhere((r) => r.id == id);
    } catch (_) {
      return null;
    }
  }
}
