-- Comentarios planos en publicaciones (1 nivel, sin hilos).
CREATE TABLE public.publicacion_comentario (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id bigint NOT NULL,
  usuario_id uuid NOT NULL,
  texto text NOT NULL,
  fecha_creacion timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT publicacion_comentario_texto_len CHECK (
    char_length(btrim(texto)) BETWEEN 1 AND 2000
  )
);

ALTER TABLE public.publicacion_comentario ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.publicacion_comentario
  ADD CONSTRAINT publicacion_comentario_publicacion_id_fkey
  FOREIGN KEY (publicacion_id) REFERENCES public.publicacion(id) ON DELETE CASCADE;

ALTER TABLE public.publicacion_comentario
  ADD CONSTRAINT publicacion_comentario_usuario_id_fkey
  FOREIGN KEY (usuario_id) REFERENCES public.usuario(id) ON DELETE CASCADE;

CREATE INDEX idx_publicacion_comentario_publicacion_id
  ON public.publicacion_comentario USING btree (publicacion_id, fecha_creacion DESC);

CREATE INDEX idx_publicacion_comentario_usuario_id
  ON public.publicacion_comentario USING btree (usuario_id);

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, UPDATE
  ON TABLE public.publicacion_comentario
  TO anon, authenticated, postgres, service_role;

GRANT USAGE, SELECT ON SEQUENCE public.publicacion_comentario_id_seq
  TO anon, authenticated, postgres, service_role;

-- Solo quien puede ver la publicación ve sus comentarios.
CREATE POLICY "Comentarios visibles si se ve la publicacion"
ON public.publicacion_comentario FOR SELECT
USING (public.puede_ver_publicacion(publicacion_id));

CREATE POLICY "Usuario autenticado comenta publicaciones visibles"
ON public.publicacion_comentario FOR INSERT
TO authenticated
WITH CHECK (
  auth.uid() = usuario_id
  AND public.puede_ver_publicacion(publicacion_id)
);

CREATE POLICY "Autor borra su propio comentario"
ON public.publicacion_comentario FOR DELETE
TO authenticated
USING (auth.uid() = usuario_id);

COMMENT ON TABLE public.publicacion_comentario IS
  'Comentarios de un nivel sobre publicacion. Sin replies en v1.';
